# Generated by Django 4.1.7 on 2023-02-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ADD', 'Добавлена'), ('WORK', 'В работе'), ('END', 'Выполнена')], default='ADD', max_length=15, verbose_name='Статус задачи'),
        ),
    ]
