# Generated by Django 4.1.7 on 2023-02-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_task_create_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Добавлена', 'Добавлена'), ('В работе', 'В работе'), ('Выполнена', 'Выполнена')], default='Добавлена', max_length=15, verbose_name='Статус задачи'),
        ),
    ]
